import type { Booking, Machine } from '@prisma/client';

// Fake booking + machine used to render a representative example of each
// email template. Same shape as a real DB row but never persisted; used
// only by the admin "send eksempel" endpoints.

export function sampleBooking(overrides: Partial<Booking> = {}): Booking & { machine: Machine | null } {
  const startDate = new Date();
  startDate.setDate(startDate.getDate() + 7);
  return {
    id: 'sample-booking-id',
    reference: 'GK-EXEMPEL',
    name: 'Ola Nordmann',
    phone: '+47 990 11 223',
    email: 'kunde@example.com',
    deliveryAddress: 'Storgata 12, 8000 Bodø',
    selfPickup: false,
    rentalType: 'weekend',
    startDate,
    customDays: null,
    preferredTime: 'Fredag ettermiddag',
    deliveryDistance: 8.4,
    deliveryFee: 0,
    basePrice: 5990,
    totalPrice: 6520,
    includedHours: 20,
    extraHours: 4,
    extraHoursCost: 716,
    totalHours: 24,
    notes: 'Skal grave dreneringsgrøft i hagen.',
    status: 'confirmed',
    customerType: 'consumer',
    termsAcceptedAt: new Date(),
    fullyPaidAt: new Date(),
    cancellationFee: null,
    machineId: 'sample-machine-id',
    machine: {
      id: 'sample-machine-id',
      name: 'Eksempelmaskin',
      category: 'Minigraver',
      model: 'R22-1 PRO',
      year: '2025',
      description: null,
      imageUrl: null,
      isActive: true,
      specs: null,
      features: null,
      included: null,
      sortOrder: 0,
      quantity: 1,
      dayPrice: null,
      weekendPrice: null,
      weekPrice: null,
      dayIncludedHours: null,
      weekendIncludedHours: null,
      weekIncludedHours: null,
      overtimeRate: null,
      preOrderHourRate: null,
      fuelTankLiters: 28,
      fuelConsumptionPerHour: 1.5,
      photoScale: 50,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    adminNote: null,
    cancelToken: 'sample-cancel-token',
    cancelTokenExpiry: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    reminderSentAt: null,
    checklistData: '{}',
    checklistToken: 'sample-checklist-token',
    stripeSessionId: null,
    stripePaymentIntentId: null,
    stripeRefundId: null,
    refundAmount: null,
    paymentProvider: null,
    vippsReference: null,
    vippsState: null,
    vippsCapturedAt: null,
    paymentMethod: 'card',
    paymentDeadline: null,
    paymentRetries: 0,
    discountKr: null,
    discountLabel: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    // Representative of a normal online booking: Stripe checkout auto-signs
    // the contract when it is frozen (see prisma/schema.prisma).
    contractSigningMethod: 'online',
    contractSigningStatus: 'signed',
    contractSentAt: startDate,
    contractSignedAt: startDate,
    contractSigningNote: null,
    digipostReference: null,  // only set on the Digipost signing path
    ...overrides,
  };
}
