import type { NextConfig } from "next";

// Content Security Policy. Tight enough to block stored-XSS payloads in
// places like the rendered TOC contract, loose enough to allow:
//   - Stripe Checkout (frame-src + script-src)
//   - Tile map images from OpenStreetMap (if any are added later)
//   - data: URLs for QR codes generated by the qrcode library
//
// `unsafe-inline` for styles is required for shadcn/Tailwind utilities and
// the inline <style> blocks in the email/contract HTML.
// `unsafe-eval` is required by React/Next.js dev tooling (Turbopack, stack
// traces). Never added in production — React does not use eval() there.
const isDev = process.env.NODE_ENV === 'development';

const cspDirectives = [
  "default-src 'self'",
  `script-src 'self' 'unsafe-inline'${isDev ? " 'unsafe-eval'" : ''} https://js.stripe.com`,
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob: https:",
  "font-src 'self' data:",
  "connect-src 'self' https://api.stripe.com https://nominatim.openstreetmap.org https://router.project-osrm.org",
  "frame-src https://js.stripe.com https://hooks.stripe.com https://checkout.stripe.com",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self' https://checkout.stripe.com",
  "object-src 'none'",
].join('; ');

const securityHeaders = [
  { key: 'Content-Security-Policy', value: cspDirectives },
  { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
  { key: 'X-Frame-Options', value: 'DENY' },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=(), interest-cohort=()' },
];

const nextConfig: NextConfig = {
  // `X-Powered-By: Next.js` on every response is free reconnaissance for an
  // attacker and tells a customer nothing (audit finding W-1).
  poweredByHeader: false,
  // standalone output was causing "client reference manifest" runtime errors
  // in Next.js 16; switching to default output + `next start` for now.
  // output: "standalone",
  reactStrictMode: true,
  // Allow LAN access during dev (next dev on 0.0.0.0 reachable from phones/tablets).
  // Without this, Next.js 16 blocks cross-origin dev requests which silently
  // breaks login (cookies appear set but the next request is rejected).
  allowedDevOrigins: [
    "192.168.0.0/16",
    "10.0.0.0/8",
    "172.16.0.0/12",
    "localhost",
  ],
  // The Tailwind stylesheet is one render-blocking request (~20 KiB gzipped,
  // 600 ms on Lighthouse's throttled mobile profile) that every first paint
  // waits on. Inlining it into the document removes that round-trip. Costs
  // the same bytes on every HTML response instead of once cached — fine for
  // a site where a visit is one page and a booking.
  experimental: {
    inlineCss: true,
  },
  images: {
    // next/image refuses any quality not listed here. 45 is for the hero,
    // which sits at 30 % opacity behind a gradient; 75 is the default for
    // everything else.
    qualities: [45, 75],
  },
  async headers() {
    return [
      {
        // Apply security headers to every route. Per-route exceptions (e.g.
        // /api/payment/stripe/webhook accepting raw POST bodies) are not
        // header-sensitive — these are response headers.
        source: '/:path*',
        headers: securityHeaders,
      },
    ];
  },
  async redirects() {
    return [
      // The terms page lives at the ASCII route /vilkar (Next.js 16 won't
      // reliably route a non-ASCII "vilkår" folder). Redirect the natural
      // Norwegian spelling — both the å-form and the URL-encoded form — so a
      // typed or bookmarked /vilkår still lands on the page.
      { source: '/vilkår', destination: '/vilkar', permanent: true },
      { source: '/vilk%C3%A5r', destination: '/vilkar', permanent: true },
    ];
  },
};

export default nextConfig;
